In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
dframe1 = pd.DataFrame(np.arange(6).reshape(2,4),index=pd.Index(['LA','SF'],name='city'),columns=pd.Index(['A','B','C','D'],name='letter'))

ValueError: total size of new array must be unchanged

In [3]:
dframe1 = pd.DataFrame(np.arange(8).reshape[2,4),index=pd.Index(['LA','SF'],name='city'),columns=pd.Index(['A','B','C','D'],name='letter'))

SyntaxError: invalid syntax (<ipython-input-3-54e5435f1ecb>, line 1)

In [4]:
dframe1 = pd.DataFrame(np.arange(8).reshape[2,4],index=pd.Index(['LA','SF'],name='city'),columns=pd.Index(['A','B','C','D'],name='letter'))

TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'

In [5]:
dframe1 = pd.DataFrame(np.arange(8).reshape(2,4),index=pd.Index(['LA','SF'],name='city'),columns=pd.Index(['A','B','C','D'],name='letter'))

In [6]:
datafram1

NameError: name 'datafram1' is not defined

In [7]:
dataframe1

NameError: name 'dataframe1' is not defined

In [8]:
dframe1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [9]:
dframe1_st = dframe1.stack

In [10]:
dframe1_st

<bound method DataFrame.stack of letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7>

In [11]:
dframe1_st.unstack('city')

AttributeError: 'function' object has no attribute 'unstack'

In [12]:
dframe1_st.unstack

AttributeError: 'function' object has no attribute 'unstack'

In [13]:
dframe1_st.unstack()

AttributeError: 'function' object has no attribute 'unstack'

In [14]:
dframe1_st = dframe1.stack()

In [15]:
dframe1_st

city  letter
LA    A         0
      B         1
      C         2
      D         3
SF    A         4
      B         5
      C         6
      D         7
dtype: int32

In [16]:
dframe1_st.unstack('city')

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [17]:
dframe1

letter  A  B  C  D
city              
LA      0  1  2  3
SF      4  5  6  7

In [18]:
dframe1.T

city    LA  SF
letter        
A        0   4
B        1   5
C        2   6
D        3   7

In [19]:
ser1 = Series([0,1,2],index=['Q','X','Y'])
ser2 = Series([4,5,6],index =['X','Y','Z'])

In [20]:
ser1
ser2

X    4
Y    5
Z    6
dtype: int64

In [21]:
ser2

X    4
Y    5
Z    6
dtype: int64

In [22]:
ser1

Q    0
X    1
Y    2
dtype: int64

In [23]:
dframe = pd.concat([ser1,ser2],keys = ['Alpha','Beta'])

In [24]:
dframe

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [25]:
dframe.T

Alpha  Q    0
       X    1
       Y    2
Beta   X    4
       Y    5
       Z    6
dtype: int64

In [26]:
dframe.stack()

AttributeError: 'Series' object has no attribute 'stack'

In [27]:
dframe.unstack()

Q    X    Y    Z
Alpha  0.0  1.0  2.0  NaN
Beta   NaN  4.0  5.0  6.0

In [28]:
attr = np.array([1,2,3,4,5])
attr[:2]

array([1, 2])

In [29]:
attr[:3]

array([1, 2, 3])

In [30]:
array = [1,2,3,4,5]

In [31]:
array[:2]

[1, 2]

In [32]:
attr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [33]:
attr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
attr[:2,1:]

array([[2, 3],
       [5, 6]])

In [35]:
attr[:2,2:]

array([[3],
       [6]])

In [36]:
attr[:2,3:]

array([], shape=(2L, 0L), dtype=int32)

In [37]:
array[2:]

[3, 4, 5]

In [38]:
array[:2]

[1, 2]

In [39]:
attr[:2,:1]

array([[1],
       [4]])

In [40]:
attr[:3,:1]

array([[1],
       [4],
       [7]])

In [41]:
attr[:3,:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
attr[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])