In [6]:
import numpy as np

In [7]:
arr1 = np.arange(0,10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr1[1:3]

array([1, 2])

In [10]:
arr_copy = arr1.copy()

In [11]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr_copy

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr_copy[1:3] = 99

In [17]:
arr_copy

array([ 0, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [18]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
arr_copy1 = arr1

In [20]:
arr_copy1[1:3] = 100

In [21]:
arr_copy1

array([  0, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [22]:
arr1

array([  0, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [23]:
arr1_copy

NameError: name 'arr1_copy' is not defined

In [24]:
arr_copy1

array([  0, 100, 100,   3,   4,   5,   6,   7,   8,   9])

In [25]:
arr_copy

array([ 0, 99, 99,  3,  4,  5,  6,  7,  8,  9])

In [26]:
arr2 = [[1,2,3],[4,5,6],[7,8,9]]

In [27]:
arr2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [28]:
arr2[:1,1:]

TypeError: list indices must be integers, not tuple

In [29]:
arr2[:2,1:]

TypeError: list indices must be integers, not tuple

In [30]:
arr2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [31]:
arr2 = np.arrat([1,2,3],[4,5,6],[7,8,9])

AttributeError: 'module' object has no attribute 'arrat'

In [32]:
arr2 = np.arrat[[1,2,3],[4,5,6],[7,8,9]]

AttributeError: 'module' object has no attribute 'arrat'

In [33]:
arr2 = np.array[[1,2,3],[4,5,6],[7,8,9]]

TypeError: 'builtin_function_or_method' object has no attribute '__getitem__'

In [34]:
arr2 = np.array([1,2,3],[4,5,6],[7,8,9])

ValueError: only 2 non-keyword arguments accepted

In [35]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [36]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2[:1,1:]

array([[2, 3]])

In [38]:
arr2[:2,2:]

array([[3],
       [6]])

In [39]:
arr2[2]

array([7, 8, 9])

In [40]:
arr2d = np.zeros([10,10])

In [41]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [42]:
arr2d = arr2d.shape[1]

In [43]:
arr2d

10L

In [44]:
arr2d = arr2d.shape[2]

AttributeError: 'long' object has no attribute 'shape'

In [45]:
arr2d = np.zeros([10,10])

In [46]:
arr2d_len = arr2d.shape[2]

IndexError: tuple index out of range

In [47]:
arr2d_len = arr2d.shape[1]

In [48]:
arr2d_len

10L

In [53]:
for i in range(arr2d_len):
    arr2d[i]=i

In [54]:
arr2d

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [55]:
arr3 =arr1.reshape(2)

ValueError: total size of new array must be unchanged

In [56]:
arr3 =arr1.reshape(1)

ValueError: total size of new array must be unchanged

In [57]:
arr3 =arr2d.reshape(2)

ValueError: total size of new array must be unchanged

In [58]:
arr3 =arr2d.reshape(1)

ValueError: total size of new array must be unchanged

In [59]:
arr3 = np.array([10])

In [60]:
arr3

array([10])

In [61]:
arr3 = np.array(50)

In [62]:
arr3

array(50)

In [63]:
arr3.reshape(10,10)

ValueError: total size of new array must be unchanged

In [64]:
arr3.reshape(10,3)

ValueError: total size of new array must be unchanged

In [65]:
arr3.reshape(10,5)

ValueError: total size of new array must be unchanged

In [66]:
arr3= np.array(50)

In [67]:
arr3.reshape(10,5)

ValueError: total size of new array must be unchanged

In [68]:
arr3.reshape((10,5))

ValueError: total size of new array must be unchanged

In [69]:
arr3 = np.arange(50)

In [70]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [71]:
arr3.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [72]:
arr3.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [73]:
np.dot(arr3,arr3.T)

40425

In [74]:
np.dot(arr3.T,arr3)

40425

In [75]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [76]:
arr3.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [77]:
arr3.reshape(10,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [78]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [79]:
arr3 = arr3.reshape(10,5)

In [80]:
np.fot(arr3.T,arr3)

AttributeError: 'module' object has no attribute 'fot'

In [81]:
np.dot(arr3.T,arr3)

array([[7125, 7350, 7575, 7800, 8025],
       [7350, 7585, 7820, 8055, 8290],
       [7575, 7820, 8065, 8310, 8555],
       [7800, 8055, 8310, 8565, 8820],
       [8025, 8290, 8555, 8820, 9085]])

In [82]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [83]:
arr3.transpose([1,0,2])

ValueError: axes don't match array

In [84]:
arr3.reshape([5,5,2])

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [85]:
arr3

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [86]:
arr3.reshape([5,5,2])

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [87]:
arr3.transpose([1,0,2])

ValueError: axes don't match array

In [88]:
arr3.transpose((1,0,2))

ValueError: axes don't match array

In [89]:
arr4 = arr3.reshape([5,5,2])

In [90]:
arr4a

NameError: name 'arr4a' is not defined

In [91]:
arr4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [92]:
arr4[1]

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [93]:
arr4[1][2]

array([14, 15])

In [94]:
arr4[1][2][1]

15

In [95]:
arr4[1][2][2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [96]:
arr4.transpose(1,0,2)

array([[[ 0,  1],
        [10, 11],
        [20, 21],
        [30, 31],
        [40, 41]],

       [[ 2,  3],
        [12, 13],
        [22, 23],
        [32, 33],
        [42, 43]],

       [[ 4,  5],
        [14, 15],
        [24, 25],
        [34, 35],
        [44, 45]],

       [[ 6,  7],
        [16, 17],
        [26, 27],
        [36, 37],
        [46, 47]],

       [[ 8,  9],
        [18, 19],
        [28, 29],
        [38, 39],
        [48, 49]]])

In [97]:
arr4.transpose(1,0,3)

ValueError: invalid axis for this array

In [98]:
arr4.transpose(1,1,2)

ValueError: repeated axis in transpose

In [99]:
arr4.transpose(0,0,2)

ValueError: repeated axis in transpose

In [100]:
arr4.transpose(0,1,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [101]:
arr4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [102]:
arr5 = np.array([2,3,4])

In [103]:
arr5

array([2, 3, 4])

In [104]:
arr5.swapaxes(0,1)

ValueError: bad axis2 argument to swapaxes

In [105]:
arr5 = np.array([[2,3,4]])

In [106]:
arr5

array([[2, 3, 4]])

In [107]:
arr5.swapaxes(0,1)

array([[2],
       [3],
       [4]])

In [108]:
arr6 = np.arange(10,10)

In [109]:
arr6

array([], dtype=int32)

In [110]:
arr6 = [[1,2],[3,4]]

In [111]:
arr6

[[1, 2], [3, 4]]

In [112]:
arr6 = np.random.randint(10)

In [113]:
arr6

0

In [114]:
arr6 = np.arange(np.random.randint(10))

In [115]:
arr6

array([0, 1])

In [116]:
arr6 = np.random.randa(10)

AttributeError: 'module' object has no attribute 'randa'

In [117]:
arr6 = np.random.randn(10)

In [118]:
arr6

array([ 0.23500652,  0.83625814,  0.55294119, -0.69515287,  0.66708738,
       -0.06323271, -0.52358562, -1.73233978,  0.1985833 ,  0.14376685])

In [119]:
arr6 = np.random.randint(10)

In [120]:
arr6

7

In [121]:
arr6 = np.random.randn(10)

In [122]:
arr6[:3]

array([ 0.39405237, -1.28561734, -0.82225188])

In [123]:
arr6

array([ 0.39405237, -1.28561734, -0.82225188,  0.57930058, -0.41027183,
        0.72098305, -0.61447115,  1.23556809, -0.21197561, -1.28994187])

In [124]:
arr6[3:]

array([ 0.57930058, -0.41027183,  0.72098305, -0.61447115,  1.23556809,
       -0.21197561, -1.28994187])

In [125]:
arr7 = np.random.randn(10)

In [126]:
arr7

array([ 0.32846386,  0.01661255, -1.53143766,  0.21806007,  1.72407812,
       -0.18893972,  0.95244236,  1.36251112, -0.88019268, -0.40384385])

In [127]:
np.maximum(arr6,arr7)

array([ 0.39405237,  0.01661255, -0.82225188,  0.57930058,  1.72407812,
        0.72098305,  0.95244236,  1.36251112, -0.21197561, -0.40384385])